FORMAT: 1A

# Listing API
The listing API is a collection of services related to listings, auctions (with or without fixed prices) and articles. Those services can be used to create a new listing to sell an article.

# Group Listings

## Listing properties

| Name      |      Type         |  Description  | Constraints | Min.-Length | Max.-Length |
|----------|:-------------:|:------:|------|:------:|------|------|
| id     |  String     | Public id to identify a listing. Choosen automatically. | None (not editable) |
| article     |  Object     | Article object. | See article properties | 1 | 1 |
| auction     |  Array[Object]     | Auction objects. | See auction properties. Other seller can join a listing when its buy now only. | 1 | * |
| hitcount     |  Integer     | Number of page hits since start of listing. | Valid Integer. | 1 | 1 |
| isbuynowonly     |  Boolean     | True if listing is buy now only. | Not null. Auction.buynowprice > 0  | 1 | 1 |

## Auction properties

| Name      |      Type         |  Description  | Constraints | Min.-Length | Max.-Length |
|----------|:-------------:|:------:|------|:------:|------|------|
| id     |  String     | Public id to identify an auction. Choosen automatically. | None (not editable) |
| condition     |  Object     | Condition of article. | Valid condition object. See condition properties. | 1 | 1 |
| seller     |  Object     | Seller object. | See *seller* properties. | 1 | 1 |
| startdate     |  Timestamp     | When was the auction started in seconds since 1970 (UTC). | Valid timestamp. | 1 | 1 |
| enddate     |  Timestamp     | When does the auction end in seconds since 1970 (UTC). | Valid timestamp. | 1 | 1 |
| shipping     |  Object     | Shipping object. | See shipping properties. | 1 | 1 |
| hasreservemet     |  Boolean     | True if reserve price was met. Always false if Listing.isbuynowonly equals true. | Not null. | 1 | 1 |
| hasreserveprice     |  Boolean     | True if reserve price is greater than zero. Always false if Listing.isbuynowonly equals true. | Not null. | 1 | 1 |
| ispickupallowed     |  Boolean     | True if article can be picked up. | Not null. | 1 | 1 |
| quantity     |  Integer     | Number of articles. If quantity is greater than one then auction is set to buy now only. | >= 1 on auction start | 0 | * |
| currency     |  Enum     | Currency. | Must be a 3 letter iso code according to [ISO-4217](http://de.wikipedia.org/wiki/ISO_4217) | 1 | 1 |
| reserveprice     |  Decimal   | The reserve price. | Valid money value.  | 0 | * |
| buynowprice     |  Decimal   | The buy now price. | Valid money value. Must be greater than zero if Listing.isbuynowonly equals true. | 0 | * |
| price     |  Decimal   | The actual price. | Valid money value, greater or equal zero. Must be less than buy now price. Must be less than reserveprice on auction start. | 0 | * |
| bids     |  Array[Object]   | Array of *bid* objects. | Valid bid object. See bid properties. | 0 | * |
| questions     |  Array[Object]   | Array of *question* objects. | Valid bid object. See bid properties. | 0 | * |
| shippingoptions     |  Array[Object]   | List of *shipping options*. If empty the article is pick up only. | Valid shippingoption object. See shippingoption properties. | 1 | 5 |
| paymentoptions     |  Array[Object]   | List of *payment options*. If empty the article can only be paid on pick up. | Valid paymentoptions object. See paymentoptions properties. | 1 | 5 |
| location     |  Object   | *Locaction* of article. Sellers country and town are used when left empty. | Valid location object. See location properties. | 0 | 1 |
| bonuspoints     |  Decimal   | Product of multiplying Auction.bonuspointfactor with Auction.price or Auction.buynowprice if Listing.isbuynowonly equals true.  | Valid decimal value.  | 0 | * |
| bonuspointfactor     |  Decimal   | Factor to calculate bonuspoints. Is a fixed value depening on auction fee.  | Valid decimal value.  | >0 | * |
| auctionfee     |  Decimal   | Auction fee in percent. Choosen by seller on auction start. | Valid decimal value.  | 0.045 | 0.2 |

## Condition properties

| Name      |      Type         |  Description  | Constraints | Min.-Value | Max.-Value |
|----------|:-------------:|:------:|------|:------:|------|------|
| condition     |  Enum     | Condition of article. | One of: NEW,REFURBISHED,USED | 1 | 1 |
| details     |  String     | Additional details about condition. | Pattern: [0-9a-zA-Z-.] + whitespace | 0 | 255 |

## Location properties

| Name      |      Type         |  Description  | Constraints | Min.-Value | Max.-Value |
|----------|:-------------:|:------:|------|:------:|------|------|
| long     |  Decimal     | Longitude or null. | Decimal. | -180.000000 | 180.000000 |
| lat     |  Decimal     | Latitude or null. | Decimal. | -90.000000 | 90.000000 |
| address     |  Object     | Address object. | See address properties for more informations. | 0 | 1 |

## Address properties

| Name      |      Type         |  Description  | Constraints | Min.-Length | Max.-Length |
|----------|:-------------:|:------:|------|:------:|------|------|
| country     |  Enum     | Country | Must be a 2 letter code according to [ISO-3166-1](https://github.com/ndheitypi/AblIMardEA-Users/wiki/Country-Codes) | 1 | 1 |
| postcode |  String     | Postcode | Pattern: [0-9] | 3 | 10 |
| phone |  String     | Phone | Pattern: [0-9.+-()] + whitespace | 0 | 50 |
| street     |  String     | Street | Pattern: [0-9a-zA-Z_-] + whitespace | 3 | 100 |
| street2     |  String     | Additional address informations. | Pattern: [0-9a-zA-Z_-] + whitespace | 0 | 100 |
| suburb     |  String     | Suburb | Pattern: [0-9a-zA-Z_-] + whitespace | 0 | 100 |
| town |  String     | Town | Pattern: [0-9a-zA-Z_-] + whitespace | 2 | 100 |

## ShippingOption properties

| Name      |      Type         |  Description  | Constraints | Min.-Length | Max.-Length |
|----------|:-------------:|:------:|------|:------:|------|------|
| id     |  String     | Public id to identify a ShippingOption. Choosen automatically. | None (not editable) |
| cost     |  Decimal   | Shipping cost. | Valid decimal value.  | 0 | * |
| currency     |  Enum     | Currency of all money values in this shipping option. | Must be a 3 letter iso code according to [ISO-4217](http://de.wikipedia.org/wiki/ISO_4217) | 1 | 1 |
| optionname     |  String     | Name of shipping option e.g. UPS Express | Pattern: [0-9a-zA-Z] + whitespace | 3 | 30 |
| insurancevalue     |  Decimal   | Max. insured value. | Valid decimal value.  | 0 | * |
| durationmin     |  Small Integer   | Minimum time till delivery in days. | Valid integer value.  | 0 | 255 |
| durationmax     |  Small Integer   | Maximum time till delivery in days. | Valid integer value.  | 0 | 255 |
| destinations     |  Array[String]   | Array of 2 letter destination countries. | Valid [ISO-3166-1](https://github.com/ndheitypi/AblIMardEA-Users/wiki/Country-Codes) country codes.  | 1 | 20 |

## PaymentOption properties

| Name      |      Type         |  Description  | Constraints | Min.-Length | Max.-Length |
|----------|:-------------:|:------:|------|:------:|------|------|
| id     |  String     | Public id to identify a PaymentOption. Choosen automatically. | None (not editable) |
| type     |  Enum     | Payment type. | One of: BANKDEPOSIT, CASH, CREDITCARD, OTHER | 1 | 1 |
| name     |  String     | Name of payment option e.g. VISA. Can be null if type is BANKDEPOSIT or CASH | Pattern: [0-9a-zA-Z_-] + whitespace | 0 | 100 |

## Question properties

| Name      |      Type         |  Description  | Constraints | Min.-Length | Max.-Length |
|----------|:-------------:|:------:|------|:------:|------|------|
| id     |  String     | Public id to identify a Question. Choosen automatically. | None (not editable) |
| askerid     |  String     | Public id of person asking this question. Choosen automatically. | None (not editable) |
| answererid     |  String     | Public id of person answering this question. Choosen automatically. | None (not editable) |
| question     |  String     | The question. | [0-9a-zA-Z!?.,] + whitespace |  > 0 | 255 |
| answer     |  String     | The answer. | [0-9a-zA-Z!?.,] + whitespace |  > 0 | 255 |

## Bid properties

| Name      |      Type         |  Description  | Constraints | Min.-Length | Max.-Length |
|----------|:-------------:|:------:|------|:------:|------|------|
| id     |  String     | Public id to identify a seller. Choosen automatically. | None (not editable) |

## Seller properties

| Name      |      Type         |  Description  | Constraints | Min.-Length | Max.-Length |
|----------|:-------------:|:------:|------|:------:|------|------|
| id     |  String     | Public id to identify a seller. Choosen automatically. | None (not editable) |

## Article properties

| Name      |      Type         |  Description  | Constraints | Min.-Length | Max.-Length |
|----------|:-------------:|:------:|------|:------:|------|------|
| id     |  String     | Public id to identify an article. Choosen automatically. | None (not editable) |
| brand     |  String     | The brand of the product. | Pattern: [0-9a-zA-Z] + whitespace | 3 | 30 |
| description     |  String     | Long Description of article. | Pattern: [0-9a-zA-Z!?.:;-\n_] + whitespace | 30 | 5000 |
| gtin     |  String     | Global Trade Item Numbers (GTINs), which include UPC (in the US), EAN (in Europe), JAN (in Japan), and ISBN | Pattern: [0-9a-zA-Z] | 0 | 14 |
| images     |  Array[Object]     | Array of image objects. | Valid image object. | 1 | 30 |
| language     |  Enum     | Language of article descriptions. | One of: DE,EN,ES,FR | 1 | 1 |
| mpn     |  String     | Manufacturer part number. The number which uniquely identifies the product to its manufacturer. | Pattern: [0-9a-zA-Z] | 0 | 30 |
| specs     |  Array[Object]     | Array of article specification objects. | Valid specification object. | 2 | 15 |
| title     |  String     | Short Description of article. | Pattern: [0-9a-zA-Z_-] + whitespace | 5 | 100 |
| categories     |  Array[Integer]     | Array of categories represented as integer. | Valid integer array. Not empty. | 1 | 3 |

## Image properties

| Name      |      Type         |  Description  | Constraints | Min.-Length | Max.-Length |
|----------|:-------------:|:------:|------|:------:|------|------|
| id     |  String     | Public id to identify a picture. Choosen automatically. | None (not editable) |
| large     |  String     | Url to large version of this image. | None (not editable) |
| medium     |  String     | Url to medium version of this image.  | None (not editable) |
| small     |  String     | Url to small version of this image.  | None (not editable) |
| thumbnail     |  String     | Url to thumbnail version of this image.  | None (not editable) |

## Specification properties

| Name      |      Type         |  Description  | Constraints | Min.-Length | Max.-Length |
|----------|:-------------:|:------:|------|:------:|------|------|
| id     |  String     | Public id to identify a spec. Choosen automatically. | None (not editable) |
| name     |  String     | Name of specification e.g. display size. | Pattern: [0-9a-zA-Z_-] + whitespace | 2 | 20 |
| value     |  String     | Value of specification e.g. 27 inch  | Pattern: [0-9a-zA-Z_-] + whitespace | 2 | 100 |
